import type { PlaylistRecord } from '../schema.js';

export const FOCUS_FALLBACK_ID = 'melolab:launch-showcase-playlist-focus-flow';

export const BUNDLED_PLAYLISTS: readonly PlaylistRecord[] = [
  {
    id: FOCUS_FALLBACK_ID,
    source: 'melolab',
    title: 'Focus Flow',
    url: 'https://melolab.ai/playlist/launch-showcase-playlist-focus-flow',
    activityTags: ['debugging', 'reviewing', 'deep_focus'],
    moodTags: ['calm', 'concentrated'],
    energy: 'low',
    focus: 'high',
    vocals: 'none',
  },
  {
    id: 'melolab:launch-showcase-playlist-suno-spotlight',
    source: 'melolab',
    title: 'Suno Spotlight',
    url: 'https://melolab.ai/playlist/launch-showcase-playlist-suno-spotlight',
    activityTags: ['feature', 'shipping'],
    moodTags: ['uplifting', 'bold'],
    energy: 'high',
    focus: 'medium',
    vocals: 'any',
  },
  {
    id: 'melolab:launch-showcase-playlist-neon-run',
    source: 'melolab',
    title: 'Neon Run',
    url: 'https://melolab.ai/playlist/launch-showcase-playlist-neon-run',
    activityTags: ['feature', 'shipping'],
    moodTags: ['driving', 'neon'],
    energy: 'high',
    focus: 'medium',
    vocals: 'low',
  },
  {
    id: 'melolab:launch-showcase-playlist-after-dark-rnb',
    source: 'melolab',
    title: 'After Dark R&B',
    url: 'https://melolab.ai/playlist/launch-showcase-playlist-after-dark-rnb',
    activityTags: ['maintenance', 'deep_focus'],
    moodTags: ['late-night', 'smooth'],
    energy: 'low',
    focus: 'medium',
    vocals: 'any',
  },
  {
    id: 'melolab:launch-showcase-playlist-cinder-dance',
    source: 'melolab',
    title: 'Cinder Dance',
    url: 'https://melolab.ai/playlist/launch-showcase-playlist-cinder-dance',
    activityTags: ['feature', 'shipping'],
    moodTags: ['warm', 'rhythmic'],
    energy: 'high',
    focus: 'low',
    vocals: 'any',
  },
  {
    id: 'melolab:launch-showcase-playlist-open-road-cinema',
    source: 'melolab',
    title: 'Open Road Cinema',
    url: 'https://melolab.ai/playlist/launch-showcase-playlist-open-road-cinema',
    activityTags: ['reviewing', 'maintenance'],
    moodTags: ['cinematic', 'open'],
    energy: 'medium',
    focus: 'high',
    vocals: 'low',
  },
];
